fo=open("library.txt","w")
fo.write("\t***LIBRARY RECORD***\n")
fo.write("Bookno\tBookname\tAuthor\n")
fo.write("1\tC++\t\tBALAGURUSAMY\n")
fo.write("2\tOS\t\tSILBERSCHERTZ\n")
fo.write("3\tOR\t\t")
fo.close()
fo=open("library.txt","r")
for line in fo.readlines():
   print(line)
fo.close()
fo=open("library.txt","a")
fo.write("L R POTTY")
fo.close()
print("\nAfter updation.....\n")
fo=open("library.txt","r+")
for line in fo.readlines():
   print(line)
fo.close()
