file = open("liibrary.txt","x")
file.close()
file = open("library.txt","w")
file.write("........Book Details.......")
file.write("\nname\tAuthor\t publisher")
file.write("\nc++\tbalaguruswamy\tdc books")
file.write("\naadujeevitha\tbenyamin\tdc books")
file.close()
file = open("library.txt","r")
for line in file.readlines():
   print(line)
file.close()
file = open("library.txt","a")
file.write("\nkayar\tthakazhi\tnew publishers")
file.close()
file = open("library.txt","r+")
for line in file.readlines():
   print(line)
file.close()
